In [23]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Amy", "Jane", "Bert", "Pam", "Colin"],
    "Age": [25, 32, 29, 40, 32, 28, 35, 21],
    "City":["London", "New York", "Paris", "Doha", "Rome", "Milan", "Tokyo", "Sydney"]
}

df = pd.DataFrame(data)

In [24]:
df["Age"]

0    25
1    32
2    29
3    40
4    32
5    28
6    35
7    21
Name: Age, dtype: int64

In [25]:
df[["Name","Age"]]

    Name  Age
0    Ali   25
1   Sara   32
2   John   29
3    Amy   40
4   Jane   32
5   Bert   28
6    Pam   35
7  Colin   21

In [26]:
# Filtering Rows
df[df["Age"] > 30]

   Name  Age      City
1  Sara   32  New York
3   Amy   40      Doha
4  Jane   32      Rome
6   Pam   35     Tokyo

In [27]:
# Creating a new column by performing math on an existing column
df["AgeIn5Years"] = df["Age"] + 5

In [28]:
df[["Name","AgeIn5Years"]]

    Name  AgeIn5Years
0    Ali           30
1   Sara           37
2   John           34
3    Amy           45
4   Jane           37
5   Bert           33
6    Pam           40
7  Colin           26

In [31]:
df.groupby("City")["Age"].mean()

City
Doha        40.0
London      25.0
Milan       28.0
New York    32.0
Paris       29.0
Rome        32.0
Sydney      21.0
Tokyo       35.0
Name: Age, dtype: float64

In [32]:
df.groupby("City")["Age"].agg(["sum", "mean", "max"])

          sum  mean  max
City
Doha       40  40.0   40
London     25  25.0   25
Milan      28  28.0   28
New York   32  32.0   32
Paris      29  29.0   29
Rome       32  32.0   32
Sydney     21  21.0   21
Tokyo      35  35.0   35